### ISSUE TITLE
FeatureUpdate: Use T4 templates instead of hard-coded strings for code generation

### ISSUE THREAD

**Issue by richardhauer** [agility/Agility.NET5.Starter#1]
An update idea: it would be much better to use T4 templates rather than hard-coded string builders for your code generation CLI, since these can be easily edited without changing the program logic.

See: [VS Doco](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019) for more info

**Comment by dkarpienia** [comment]
@richardhauer Yes, that is a great idea! I think the community would love to see that implementation and which is why I made the project public. So please feel free to fork and share your ideas.
